# main menu
[[main]]
name = "Beranda"
url = ""
weight = 1

[[main]]
name = "Tentang Kami"
url = "tentang-kami/"
weight = 2

[[main]]
name = "Portofolio"
url = "portofolio/"
weight = 3

[[main]]
name = "Artikel"
url = "blog/"
weight = 4
  
[[main]]
name = "Hubungi Kami"
url = "kontak/"
weight = 5

#[[main]]
#weight = 4
#name = "Pages"
#hasChildren = true

#  [[main]]
#  parent = "Pages"
#  name = "Blog Details"
#  url = "blog/post-1/"
#  weight = 1

#  [[main]]
#  parent = "Pages"
#  name = "Terms & Conditions"
#  url = "terms-and-conditions/"
#  weight = 7


# footer menu
[[footer]]
name = "Tentang Kami"
url = "tentang-kami/"
weight = 1

[[footer]]
name = "Portofolio"
url = "portofolio/"
weight = 2

[[footer]]
name = "Artikel"
url = "blog/"
weight = 3