#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.webp"
# use `x` with logo_width, example: "100x"
logo_width = "240x"
# logo text will only show when logo is missing.
logo_text = "Andromeda"
# OpenGraph / Twitter Card metadata
description = "Jasa Konstruksi & General Kontraktor Jogja - CV. Karya Anansa Jaya"
author = "CV. Karya Anansa Jaya"
image = "images/logo.png"                # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "Jasa Konstruksi & General Kontraktor Jogja. Memberikan kepercayaan berdasarkan kualitas, ketepatan, serta harga yang kompetitif."

# contact form action
contact_form_action = "" # contact form works with https://formspree.io

# copyright
copyright = "&copy; 2022 - CV. Karya Anansa Jaya"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""

# buy premium popup
buy_premium_popup = false

# Main Sections
mainSections = ["blog"]

# reading time for blog posts
reading_time = true

# contact information
[contact_info]
address = "Perumahan Alam Citra Blok F-33, Panggungharjo, Sewon, Bantul, Yogyakarta 55188"
phone = "081270054464"
email = "kajsaja@yahoo.com"

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = false
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Konsultasi Sekarang"
link = "https://wa.me/6281270054464?text=Halo%20CV%20Karya%20Anansa%20Jaya%2C%0ASaya%20mau%20bertanya%20tentang%20jasa%20konstruksi."

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Kepercayaan anda adalah tujuan kami"
content = "Konsultasikan kebutuhan pembangunan rumah anda dengan kami. Tim kami akan memberikan support secara professional dan penuh tanggung jawab"
button = "Konsultasi Sekarang"
button_link = "https://wa.me/6281270054464?text=Halo%20CV%20Karya%20Anansa%20Jaya%2C%0ASaya%20mau%20bertanya%20tentang%20jasa%20konstruksi"

############################# social site ########################
[[social]]
title = "Karya Anansa Jaya"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "#"

[[social]]
title = "Karya Anansa Jaya"
icon = "lab la-twitter"  # https://icons8.com/line-awesome
link = "#"

[[social]]
title = "Karya Anansa Jaya"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "#"

[[social]]
title = "Karya Anansa Jaya"
icon = "lab la-instagram" # https://icons8.com/line-awesome
link = "#"
